name: Elixir CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine
      env:
        MIX_ENV: test

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
    - uses: actions/checkout@v1
    - name: Install Alpine Deps
      run: apk add --update openssl ncurses-libs build-base git --no-cache
    - name: Install Hex
      run: |
        mix local.rebar --force
        mix local.hex --force
    - name: Get and Compile deps
      run: mix do deps.get, deps.compile
    - name: Run Tests
      run: |
        mix test
        mix coveralls.github
      env:
        DB_HOST: postgres
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
