name: Elixir CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install Hex
      run: |
        mix local.rebar --force
        mix local.hex --force
    - name: Install Alpine Deps
      run: apk add --update openssl ncurses-libs build-base --no-cache
    - name: Get and Compile deps
      run: mix do deps.get, deps.compile
    - name: Run Tests
      run: mix test
